import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./globals.scss";
import SmoothScrolling from "@/components/SmoothScrolling";

const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/custom/Header";
import { AuthProvider } from "@/context/AuthProvider";
import { auth } from "@/auth";
import { SessionType } from "@/types/next-auth";

export const metadata: Metadata = {
  title: "Auth.js V5",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <AuthProvider initialSession={session}>
        <body className={inter.className}>
          <SmoothScrolling>
            <main>{children}</main>
          </SmoothScrolling>
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
